TOPBAR_TITLE = "Online Work Buddy"
STUDENT_LOGIN_TITLE = "Student Login"
STUDENT_REG_TITLE   = "Student Registration"
EMPLOYEE_REGISTER_TITLE = "Employee Registartion"
EMPLOYEE_LOGIN_TITLE = "Employee Login"
DASHBOARD_TITLE = "Dashboard"