BACKEND_BASE_URL = "http://127.0.0.1:8080"
STUDENT_REGISTRTION_ENDPOINT = "/register/student_register"
USER_LOGIN_ENDPOINT = "/user/login"
STRESS_BLINK_ENDPOINT = "/stress_blink_value/add_stress_blink_values"
FILE_PATH = "/home/mukesh/access_token/"
EMPLOYEE_REGISTARTOIN_ENDPOINT = "/register/employee_register"

STRESS_BLINK_DETECTOR = "/home/mukesh/hackfest/py_charmer_hackfest_project/pycharmer_project_desktop_app/stress_detection_module/detection_process_code.py"
SRESS_BLINK_DATA_GET = "/stress_blink_value/get_stress_blink_values"
GET_STEP_COUNT_END_POINT = "https://fastapi.surdebmalya11.repl.co/get_stepcounts"
GET_BOWSING_DETAILS = "/browsing_history/get_user_browsing_details"
GET_ALERT_END_POINT = "/alert/get_alert"